sudo: required
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
services:
  - docker
before_install:
  - sudo docker pull centos:7
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then pip install -r requirements/python2.6.txt; fi
  - pip install coveralls
  - python setup.py -q install
script:
  - nosetests -v -w nfsinkhole --include=docker --with-coverage --cover-package=nfsinkhole
  - sudo docker network create --driver=bridge net1 --subnet=172.17.0.0/24
  - sudo docker network create --driver=bridge net2 --subnet=172.17.1.0/24
  - sudo docker run -d --name nfsinkholevm --network net1 -t centos:7 bash
  - sudo docker network connect net2 nfsinkholevm
  - sudo docker ps -a | grep nfsinkholevm
  - sudo docker network ls
  - sudo docker cp $TRAVIS_BUILD_DIR nfsinkholevm:/root/nfsinkhole
  - sudo docker exec nfsinkholevm /bin/sh -c "yum -y install net-tools"
  - sudo docker exec nfsinkholevm /bin/sh -c "ifconfig"
  - sudo docker exec nfsinkholevm /bin/sh -c "ls -al /root/nfsinkhole"
  - sudo docker exec nfsinkholevm /bin/sh -c "cd /root/nfsinkhole/ && python setup.py install"

after_success:
  - coveralls --rcfile=.coveragerc
