sudo: required
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
services:
  - docker
before_install:
  - chmod ugo+x nfsinkhole/tests/travis_tests.sh
install:
  - pip install coveralls
  - python setup.py install
script: ./nfsinkhole/tests/travis_tests.sh
after_script:
  - coveralls --rcfile=.coveragerc
