sudo: required
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
services:
  - docker
before_install:
  - chmod ugo+x nfsinkhole/tests/travis_tests.sh
  - sudo apt-get -qq update
  - sudo apt-get install -y selinux-basics selinux-policy-default auditd
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then pip install -r requirements/python2.6.txt; fi
  - pip install coveralls
  - python setup.py install
script: ./nfsinkhole/tests/travis_tests.sh
after_success:
  - coveralls --rcfile=.coveragerc
