sudo: required
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
services:
  - docker
before_install:
  - sudo docker pull centos:7
install:
  - docker ps
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6* ]]; then pip install -r requirements/python2.6.txt; fi
  - pip install coveralls
  - python setup.py -q install
script:
  - nosetests -v -w nfsinkhole --include=docker --with-coverage --cover-package=nfsinkhole
  - docker run centos:7 /bin/sh -c "ls -al"
after_success:
  - coveralls --rcfile=.coveragerc
