sudo: required
language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
services:
  - docker
before_install:
  - chmod ugo+x nfsinkhole/tests/travis_tests.sh
script: ./nfsinkhole/tests/travis_tests.sh
